# Generated by Django 4.2.30 on 2026-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_auditlog_dataupload_delete_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupload",
            name="column_mapping",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
