# Generated by Django 4.2.30 on 2026-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_dataupload_column_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="order_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["order_date", "customer"], name="dashboard_s_order_d_6adc7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer", "total_sales"],
                name="dashboard_s_custome_5ece07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["product", "total_sales"], name="dashboard_s_product_a8dc7a_idx"
            ),
        ),
    ]
