# Generated by Django 6.0.4 on 2026-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_sale_order_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_time_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sale",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
