# Generated by Django 6.0.4 on 2026-04-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0006_customer_age_customer_gender_sale_delivery_time_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
