# Generated by Django 6.0.4 on 2026-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_sale_is_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
