# Generated by Django 4.2.30 on 2026-05-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customer_customer_id_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['order_date', 'total_sales', 'profit'], name='dashboard_s_order_d_2996dc_idx'),
        ),
    ]
