# Generated by Django 4.2.30 on 2026-05-04 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_alter_customer_region_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Analysis', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='analysissession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='dashboard.analysissession'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='dashboard.analysissession'),
        ),
        migrations.AddField(
            model_name='product',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.analysissession'),
        ),
        migrations.AddField(
            model_name='sale',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='dashboard.analysissession'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['session', 'order_date'], name='dashboard_s_session_1c8931_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('session', 'name', 'region', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('session', 'name', 'category', 'sub_category')},
        ),
    ]
