# Generated by Django 4.2.30 on 2026-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_analysissession_sale_dashboard_s_session_1c8931_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_id__isnull', False), models.Q(('customer_id', ''), _negated=True)), fields=('session', 'customer_id'), name='unique_customer_id_per_session'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('product_id__isnull', False), models.Q(('product_id', ''), _negated=True)), fields=('session', 'product_id'), name='unique_product_id_per_session'),
        ),
    ]
