# Generated by Django 6.0.4 on 2026-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_customer_unique_customer_id_per_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(db_index=True, max_length=100)),
                ("task_label", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("result", models.TextField(blank=True, default="")),
                ("duration_ms", models.IntegerField(default=0)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
    ]
